apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy53
  labels:
    app: autodeploy53
  namespace: namespace-workflow-1714386418046
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy53
  template:
    metadata:
      labels:
        app: autodeploy53
    spec:
      containers:
        - name: autodeploy53
          image: acrworkflow1714386418046.azurecr.io/image-workflow-1714386418046:latest
          ports:
            - containerPort: 5000