apiVersion: v1
kind: Service
metadata:
  name: autodeploy53
  namespace: namespace-workflow-1714386418046
spec:
  type: LoadBalancer
  selector:
    app: autodeploy53
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000